spring:
  main:
    banner-mode: off
  profiles:
    include:
      - integration  #uncomment for integration

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Demo
    username: AdminDemo
    password: password
  sql:
    init:
      schema-locations: 'classpath:db/MTB mysql.sql'
      data-locations: 'classpath:db/MTB dml.sql'
      platform: mysql
      #      mode: never  # use for production
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 50

